# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Dmitriy/AppData/Local/Temp/WindowGwMRQF.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 661, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GlobalMenu = QtWidgets.QVBoxLayout()
        self.GlobalMenu.setObjectName("GlobalMenu")
        self.MenuPorts = QtWidgets.QHBoxLayout()
        self.MenuPorts.setObjectName("MenuPorts")
        self.ListPorts = QtWidgets.QComboBox(self.layoutWidget)
        self.ListPorts.setObjectName("ListPorts")
        self.MenuPorts.addWidget(self.ListPorts)
        self.ButOpenPort = QtWidgets.QPushButton(self.layoutWidget)
        self.ButOpenPort.setObjectName("ButOpenPort")
        self.MenuPorts.addWidget(self.ButOpenPort)
        self.ButClosePort = QtWidgets.QPushButton(self.layoutWidget)
        self.ButClosePort.setObjectName("ButClosePort")
        self.MenuPorts.addWidget(self.ButClosePort)
        self.GlobalMenu.addLayout(self.MenuPorts)
        self.MenuChangeGas = QtWidgets.QVBoxLayout()
        self.MenuChangeGas.setObjectName("MenuChangeGas")
        self.ButCalibration = QtWidgets.QPushButton(self.layoutWidget)
        self.ButCalibration.setObjectName("ButCalibration")
        self.MenuChangeGas.addWidget(self.ButCalibration)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.spinBoxMin = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxMin.setObjectName("spinBoxMin")
        self.spinBoxMin.setMaximum(999999)
        self.spinBoxMin.setValue(0)

        self.horizontalLayout_2.addWidget(self.spinBoxMin)
        self.spinBoxMax = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxMax.setObjectName("spinBoxMax")
        self.spinBoxMax.setMaximum(999999)
        self.spinBoxMax.setValue(0)

        self.horizontalLayout_2.addWidget(self.spinBoxMax)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.SlidePower = QtWidgets.QSlider(self.layoutWidget)
        self.SlidePower.setMaximum(800)
        self.SlidePower.setMinimum(3200)
        self.SlidePower.setValue(0)
        self.SlidePower.setPageStep(0)
        self.SlidePower.setOrientation(QtCore.Qt.Horizontal)
        self.SlidePower.setObjectName("SlidePower")

        self.verticalLayout.addWidget(self.SlidePower)
        self.valueGas = QtWidgets.QLabel(self.layoutWidget)
        self.valueGas.setEnabled(True)
        self.valueGas.setAutoFillBackground(False)
        self.valueGas.setScaledContents(False)
        self.valueGas.setWordWrap(False)
        self.valueGas.setIndent(250)
        self.valueGas.setObjectName("valueGas")
        self.verticalLayout.addWidget(self.valueGas)
        self.MenuChangeGas.addLayout(self.verticalLayout)
        self.GlobalMenu.addLayout(self.MenuChangeGas)
        self.horizontalLayout.addLayout(self.GlobalMenu)
        self.butRefresh = QtWidgets.QPushButton(self.layoutWidget)
        self.butRefresh.setObjectName("butRefresh")
        self.horizontalLayout.addWidget(self.butRefresh)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Window"))
        self.ButOpenPort.setText(_translate("MainWindow", "открыть порт"))
        self.ButClosePort.setText(_translate("MainWindow", "закрыть порт"))
        self.ButCalibration.setText(_translate("MainWindow", "Калибровка"))
        self.valueGas.setText(_translate("MainWindow", "0"))
        self.butRefresh.setText(_translate("MainWindow", "Обновить список портов"))

    def onStartUp(self,gas_min,gas_max,gas):
        self.spinBoxMin.setValue(gas_min)
        self.spinBoxMax.setValue(gas_max)
        self.SlidePower.setMinimum(gas_min)
        self.SlidePower.setMaximum(gas_max)
        self.SlidePower.setValue(gas)
        self.SlidePower.setProperty("value", gas)

