# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Дмитрий (и Лера)/AppData/Local/Temp/WindowSrVkfw.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SlidePower = QtWidgets.QSlider(self.centralwidget)
        self.SlidePower.setGeometry(QtCore.QRect(10, 500, 251, 21))
        self.SlidePower.setMaximum(50)
        self.SlidePower.setPageStep(0)
        self.SlidePower.setProperty("value", 0)
        self.SlidePower.setOrientation(QtCore.Qt.Horizontal)
        self.SlidePower.setObjectName("SlidePower")
        self.spinBoxMin = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxMin.setGeometry(QtCore.QRect(10, 530, 61, 20))
        self.spinBoxMin.setMaximum(10000)
        self.spinBoxMin.setObjectName("spinBoxMin")
        self.spinBoxMax = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxMax.setGeometry(QtCore.QRect(200, 530, 61, 20))
        self.spinBoxMax.setMaximum(10000)
        self.spinBoxMax.setObjectName("spinBoxMax")
        self.ButOpenPort = QtWidgets.QPushButton(self.centralwidget)
        self.ButOpenPort.setGeometry(QtCore.QRect(120, 0, 121, 31))
        self.ButOpenPort.setObjectName("ButOpenPort")
        self.ButClosePort = QtWidgets.QPushButton(self.centralwidget)
        self.ButClosePort.setGeometry(QtCore.QRect(240, 0, 121, 31))
        self.ButClosePort.setObjectName("ButClosePort")
        self.ListPorts = QtWidgets.QComboBox(self.centralwidget)
        self.ListPorts.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.ListPorts.setObjectName("ListPorts")
        self.SlidePower.raise_()
        self.spinBoxMin.raise_()
        self.spinBoxMax.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Window"))
        self.ButOpenPort.setText(_translate("MainWindow", "открыть порт"))
        self.ButClosePort.setText(_translate("MainWindow", "закрыть порт"))
