# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'C:/Users/Dmitriy/AppData/Local/Temp/WindowevlSKF.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSerialPort import QSerialPort, QSerialPortInfo
from PyQt5.QtCore import QIODevice
import sys



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1046, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 10, 1041, 611))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GlobalMenu = QtWidgets.QVBoxLayout()
        self.GlobalMenu.setObjectName("GlobalMenu")
        self.MenuPorts = QtWidgets.QHBoxLayout()
        self.MenuPorts.setObjectName("MenuPorts")
        self.ListPorts = QtWidgets.QComboBox(self.widget)
        self.ListPorts.setObjectName("ListPorts")
        self.MenuPorts.addWidget(self.ListPorts)
        self.ButOpenPort = QtWidgets.QPushButton(self.widget)
        self.ButOpenPort.setObjectName("ButOpenPort")
        self.MenuPorts.addWidget(self.ButOpenPort)
        self.ButClosePort = QtWidgets.QPushButton(self.widget)
        self.ButClosePort.setObjectName("ButClosePort")
        self.MenuPorts.addWidget(self.ButClosePort)
        self.GlobalMenu.addLayout(self.MenuPorts)
        self.butRefresh = QtWidgets.QPushButton(self.widget)
        self.butRefresh.setObjectName("butRefresh")
        self.GlobalMenu.addWidget(self.butRefresh)
        self.MenuChangeGas = QtWidgets.QVBoxLayout()
        self.MenuChangeGas.setObjectName("MenuChangeGas")
        self.ButCalibration = QtWidgets.QPushButton(self.widget)
        self.ButCalibration.setObjectName("ButCalibration")
        self.MenuChangeGas.addWidget(self.ButCalibration)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBoxMin = QtWidgets.QSpinBox(self.widget)
        self.spinBoxMin.setObjectName("spinBoxMin")
        self.horizontalLayout_2.addWidget(self.spinBoxMin)
        self.spinBoxMax = QtWidgets.QSpinBox(self.widget)
        self.spinBoxMax.setObjectName("spinBoxMax")
        self.horizontalLayout_2.addWidget(self.spinBoxMax)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.SlidePower = QtWidgets.QSlider(self.widget)
        self.SlidePower.setMaximum(50)
        self.SlidePower.setPageStep(0)
        self.SlidePower.setProperty("value", 50)
        self.SlidePower.setOrientation(QtCore.Qt.Horizontal)
        self.SlidePower.setObjectName("SlidePower")
        self.verticalLayout.addWidget(self.SlidePower)
        self.MenuChangeGas.addLayout(self.verticalLayout)
        self.GlobalMenu.addLayout(self.MenuChangeGas)
        self.horizontalLayout.addLayout(self.GlobalMenu)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.valueGas = QtWidgets.QLabel(self.widget)
        self.valueGas.setAutoFillBackground(False)
        self.valueGas.setAlignment(QtCore.Qt.AlignCenter)
        self.valueGas.setObjectName("valueGas")
        self.verticalLayout_2.addWidget(self.valueGas)
        self.debugWindow = QtWidgets.QTextBrowser(self.widget)
        self.debugWindow.setObjectName("debugWindow")
        self.verticalLayout_2.addWidget(self.debugWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Window"))
        self.ButOpenPort.setText(_translate("MainWindow", "открыть порт"))
        self.ButClosePort.setText(_translate("MainWindow", "закрыть порт"))
        self.butRefresh.setText(_translate("MainWindow", "Обновить список портов"))
        self.ButCalibration.setText(_translate("MainWindow", "Калибровка"))
        self.valueGas.setText(_translate("MainWindow", "TextLabel"))


    def onStartUp(self, gas_min, gas_max, gas):
        self.spinBoxMin.setMaximum(999999)
        self.spinBoxMin.setValue(0)
        self.spinBoxMax.setMaximum(999999)
        self.spinBoxMax.setValue(0)
        self.spinBoxMin.setValue(gas_min)
        self.spinBoxMax.setValue(gas_max)
        self.SlidePower.setMinimum(gas_min)
        self.SlidePower.setMaximum(gas_max)
        self.SlidePower.setValue(gas)
        self.SlidePower.setProperty("value", gas)

    def sendDb(self,txt):
        self.debugWindow.append(txt)


app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)



